name: Docker Build And Push GitHub Container Registry

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: docker build -t ghcr.io/flarion-development/phone-number-chk:$(date +%s) .
      - name: Push
        run: docker push ghcr.io/flarion-development/phone-number-chk:$(date +%s)
      
      
